### ISSUE TITLE
Photosynthesis.jl name

### ISSUE THREAD

**Issue by rafaqz** [Yujie-W/Photosynthesis.jl#23]
Hi! great to find this repo, and all the modular repos you have like PlantHydraulics.jl

I was literally about to register https://github.com/rafaqz/Photosynthesis.jl but I think this package will be better. I don't really work on photosynthesis that much these days anyway. Anyway, the name is yours.

**Comment by Yujie-W** [comment]
Actually, I am a postdoc in Christian's lab. We spent a lot time to make the land model modular. I read your code, and remember that Christian showed me some of those as examples of mutiple dispatch. I, however, moved the empirical stomatal model part to a seprate package StomataModels, together with other stomatal models (empirical or optimal).

**Comment by rafaqz** [comment]
I figured that, I just hadn't noticed that you were breaking up the land model into separate packages. It's great for related fields. We can use these components in our models without having to understand/install the whole land model. It should make your models more scrutinised and trusted in the end as well if people use them for other things.
