### ISSUE TITLE
reference of glc

### ISSUE THREAD

**Issue by kongdd** [Yujie-W/Photosynthesis.jl#32]
Dear Yujie, 

I find that many function names with the postfix of `_glc`. Could you tell me what the meaning of `glc`? It will be great if have references.

Thank you!
Dongdong

**Comment by Yujie-W** [comment]
It is in the documentation: https://github.com/Yujie-W/Photosynthesis.jl/blob/main/src/photosynthesis/model.jl#L85, meaning leaf diffusive conductance for CO2, glc = A / (Ca - Ci)

**Comment by kongdd** [comment]
Clear now. Thank for your quick response.
